# Generated by Django 2.2.14 on 2021-06-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('b+', 'B+'), ('b-', 'B-'), ('a+', 'A+'), ('a-', 'A-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=3)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('any_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('required_blood_group', models.CharField(choices=[('b+', 'B+'), ('b-', 'B-'), ('a+', 'A+'), ('a-', 'A-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=3)),
                ('purpose', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
