# Generated by Django 2.2.14 on 2021-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_number', models.IntegerField(blank=True, null=True)),
                ('logo_image', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
