# Generated by Django 3.2.3 on 2021-06-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0004_auto_20210620_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
